### ISSUE TITLE
Implement 'TodoDB'

### ISSUE THREAD

**Issue by ChShersh** [StasyaGera/todo-cli#6]
Something is already described under #4 in comments.

So, you have function like _change `Todo` item_. But now you need to store all available tags and all `Todo` items. It's not efficient to lookup through whole `Todo` tree to gather all tags. You can't add arbitrary tags to issue, only those ones, which are available. So you should also support operation to create new `Tag`.

For now you can have:

```haskell
data TodoDB = TodoDB Todos Tags -- with record fields of course
```

And implement all functions to manipulate with todo data base.

**Comment by StasyaGera** [comment]
How is it supposed to work?
I mean, user is able to call a `Todo` constructor or our `defTodo` function, both of which do not now about `TodoDB` so we are going to have an unregistered `Todo` item.
Situation with tags is similar: they can first appear at the time of `Todo` object construction.

**Comment by ChShersh** [comment]
@StasyaGera This will work in the following way:

Users can't use `Todo` constructor directly. Function `createTodo` will have type:

```haskell
createTodo 
    :: TodoDB  -- todo data base
    -> TodoFields -- all required data to create single TODO item
    -> Either CreateError (Todo, TodoDB) -- created TODO item with new DB
```

After we learn new cool monads like `State` monad this all will be written much cooler and simpler.

But the idea is the following: you shouldn't be able to create `Todo` item with unregistering tags. You should add required tags first.

Another design solution: you specify tags for `Todo` item and all new tags are added to `TodoDB`. But I think this is not a good solution...
